### ISSUE TITLE
No Scripts added on Page

### ISSUE THREAD

**Issue by joside** [terrylinooo/wp-mermaid#5]
I have no Mermaid-Scripts on my pages. The Scripts are added and working if I am logged in. The Diagrams I wanted to show are not rendered if I am not logged in.
(https://josi.de/deine-waschmaschine-wird-smart-lass-sie-mit-node-red-und-google-home-sprechen/)

**Comment by terrylinooo** [comment]
It's possible that your website has enabled some caching functionality. Please turn it off or clear the cache and try again.

**Comment by joside** [comment]
Sorry, cleared the cache but still the same. 
Also disabled and reenabled another plugin which showed immediately effect in the source code of the page.

**Comment by joside** [comment]
removed plugin for the moment.
